{
  imports = [
    ./fastfetch/default.nix
    ./fish/default.nix
    ./ghostty/default.nix
    ./lowfi/default.nix
    ./mpv/default.nix
    ./starship/default.nix
    ./git/default.nix
    ./helix/default.nix
    ./MangoHud/default.nix
    ./single_files.nix
    ./zed/default.nix
    ./vicinae.nix
    ./direnv.nix
    ./zen-browser/default.nix
    ./media.nix
    ./social.nix
    ./fonts.nix
    ./games.nix
    ./system.nix
    ./extra.nix
  ];
}
