
# Automatically installs and run Shizuku on connected android devices.
# Gets ran from udev when a new usb android device gets connected
function shizuku_start -d "Start shizuku on the connected device if it isn't already running"
    # hack for notify-send to be able to connec to DBUS under udev
    set -x DBUS_SESSION_BUS_ADDRESS unix:path=/run/user/1000/bus

    if test -z (adb devices | sed '2p;d')
        notify-send -e -a Android "Searching for device" "No devices found!" -i smartphone
        return
    end

    # Check if shizuku is installed
    set shizuku_is_installed (adb shell pm list packages | rg shizuku &> /dev/null && echo yes || echo no)

    if test $shizuku_is_installed = no
        set install (notify-send -e -a Android "New android device detected !" "This device does not appear to have shizuku installed, do you wish to install and run it?" -i smartphone --action=yes="Yes, install the latest version" --action=no="No")
        switch $install
            case yes
                set notif_num (notify-send -ep -a Android Installer "Downloading latest shizuku..." -i smartphone)
                set url (xh -I GET https://api.github.com/repos/RikkaApps/Shizuku/releases | jq -r ".[0].assets[0].browser_download_url")
                xh -I -q --download $url --output /tmp/shizuku.apk
                set notif_num (notify-send -ep -a Android Installer "Installing shizuku..." -i smartphone -r "$notif_num")
                adb install /tmp/shizuku.apk
                set notif_num (notify-send -ep -a Android Installer "Install complete..." -i smartphone -r "$notif_num")
                adb shell am start-activity -S moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity

                # wait until the file are generated by the manager before running them
                # terrible implementation of watch, since watch cannot run in the environment made by udev
                set counter 0
                while adb shell "test ! \( -f /sdcard/Android/data/moe.shizuku.privileged.api/start.sh \)"; and test "$counter" -le 9
                    set counter (math $counter + 1)
                    echo "Waiting for manager to generate files"
                    sleep 0.5
                end

            case "no", '*'
                return

        end

    end

    set shizuku_pid (adb shell ps -o PID,NAME | rg shizuku_server | cut -d' ' -f1)
    if test -n "$shizuku_pid"
        echo "Shizuku is already running on device with pid $shizuku_pid"
        return
    end
    adb shell /data/app/~~5yUOQNttTA6taujdSXq3SQ==/moe.shizuku.privileged.api-gvBa9CcvQELt8vtGkvG8Sg==/lib/arm64/libshizuku.so
    notify-send -ep -a Android "Auto Start" "Shizuku has been started !" -i smartphone -r "$notif_num"

end
